### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lordavgen** [Caleb-Wishart/tile-painter#3]
At the time of the rocket launch, I tried to open the warehouse on the left.
![Screenshot 2024-08-09 062200](https://github.com/user-attachments/assets/032b6114-0d14-422c-9734-90a11d40fe46)

**Comment by Caleb-Wishart** [comment]
Huh, interesting.

Thanks for the report, and on GH too!

What mod is the warehouse from?
Does it only occur at the time of rocket launch?


Regardless, I'll try and beef up the checks I do when accessing the cursor stack to fix this issue and publish a patch soon.

**Comment by lordavgen** [comment]
when re-launching the rocket, I noticed that the standard interface disappears (this is normal behavior), and at this point, any click on the screen causes an error.

I think the warehouse mod has nothing to do with it, but still here it is
https://mods.factorio.com/mod/Warehousing

**Comment by Caleb-Wishart** [comment]
Resolved in v1.0.2
